version: "3"

services:
  digital-library:
    container_name: digital-library
    build: .
    ports:
      - "8080:8080"
  mongodb:
    container_name: digital-library-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/mongodb
volumes:
  data: